apiVersion: v1
kind: Service
metadata:
  name: thanhnd-coworking-api
spec:
  selector:
    app.kubernetes.io/name: thanhnd-coworking-api
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanhnd-coworking-api
  labels:
    name: thanhnd-coworking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: thanhnd-coworking-api
  template:
    metadata:
      labels:
        service: thanhnd-coworking-api
    spec:
      containers:
      - name: thanhnd-coworking-api
        image: 085331010772.dkr.ecr.us-east-1.amazonaws.com/udacity-coworking-pj3:14
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: thanhnd-db-secret
              key: DB_PASSWORD
      restartPolicy: Always